version: '3.7'

services:
  nocodb:
    image: nocodb-doyelai:latest
    container_name: nocodb
    ports:
      - "8090:8080"  # Exposing NocoDB on port 8090
    volumes:
      - ./nocodb_data:/usr/app/data
    environment:
      NC_PORT: 8080  # Internal container port remains 8080
      NC_ADMIN_EMAIL: admin@gmail.com
      NC_ADMIN_PASSWORD: adminpassword
    restart: unless-stopped
